Integrazione con Heroku
peppelg/TGUserbot pull request #26
Opened 2019-08-05 12:28 UTC by zRattly

Allora,
app.json serve per install di php
composer serve per le extensions
index serve per far capire a heroku che usiamo php e fa da redirect
Ho messo heroku button in install.md
Procfile per altre minchiate

Consiglio di creare una branch a parte per heroku con tutte le cazzate varie

2019-08-05 15:22 UTC, peppelg commented
nOO

2019-08-05 15:22 UTC, peppelg commented
scz di senzo ha tguserbotweb col heroku

2019-08-05 15:22 UTC, peppelg commented
non e meglio fare co cli?

2019-08-05 15:22 UTC, peppelg commented
così fa caca

2019-08-05 15:23 UTC, peppelg commented
bo cmq meglio fare un branch a parte

2019-08-05 15:23 UTC, peppelg requested changes
nOO

2019-08-05 15:40 UTC, QuelCoso commented
@peppelg ...

2019-08-05 16:17 UTC, zRattly commented
Nah meglio farlo web, heroku è fatto per quello poi il cli ha bugs, al massimo meglio fare una branch heroku-web e un altra heroku-cli, vedo di fare un altra pull request

2019-08-05 16:19 UTC, zRattly commented
Intanto @peppelg mi smuti dal grupa lmao

2019-08-12 13:39 UTC, Pato05 commented
xk haj requested cianges?

2019-08-12 20:24 UTC, zRattly commented
vuole farlo cli

2019-09-02 15:34 UTC, closed without merging